name: Push Docker image to Docker Hub

on:
  # release:
  #   types: [published]
  push:
    # tags:
    #   - 'v*' # 匹配所有以 v 开头的 tag，例如 v1.0.0
    # branches:
    #   - main
    #   - dev
  
jobs:
  # Publishing and installing a package with GitHub Actions: https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions
  push_to_registry:
    name: Push Docker image to Docker Hub

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go_version:
          # - "1.20"
          # - "1.21"
          # - "1.23"
          - "1.24"
        platforms:
          # - linux/amd64
          - linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # with:
        #   # https://github.com/docker/build-push-action/issues/761
        #   driver-opts: |
        #     image=moby/buildkit:v0.10.6
           
      - name: Determine image tags
        id: tags
        run: |
          GO_TAG=go${{ matrix.go_version }}
          PLATFORM_TAG="${GO_TAG}-${{ matrix.platforms }}"
          # 替换平台中的 `/` 为 `_`
          PLATFORM_TAG=$(echo "$PLATFORM_TAG" | tr '/' '_')
          echo "tags=$GO_TAG" >> $GITHUB_OUTPUT
          echo "platform_tag=$PLATFORM_TAG" >> $GITHUB_OUTPUT
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          else
            echo "tag=" >> $GITHUB_OUTPUT
          fi

      # group: login and push to GHCR
      - name: Log in to GHCR
        # if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch image for Go ${{ matrix.go_version }} on ${{ matrix.platforms }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfiles/Dockerfile
          push: true # ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' ||startsWith(github.ref, 'refs/tags/') }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.tags.outputs.platform_tag }}
            ghcr.io/${{ github.repository }}:${{ steps.tags.outputs.tags }}
          # ${{ steps.tags.outputs.tags != '' && format('ghcr.io/{0}:{1}', github.repository, steps.tags.outputs.tags) }}
          # labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GO_VERSION=${{ matrix.go_version }}
          platforms: |
            ${{ matrix.platforms }}